apiVersion: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://localhost:8080
    jsonData:
      graphiteVersion: "1.1"
  
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://localhost:9090
  
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: site
    user: grafana
    password: grafana
    url: http://localhost:8086
    jsonData: 
      timeInterval: "15s"

  - name: OpenTsdb
    type: opentsdb
    access: proxy
    url: http://localhost:4242
    jsonData: 
      tsdbResolution: 1
      tsdbVersion: 1

  - name: Elastic
    type: elasticsearch
    access: proxy
    database: "[metrics-]YYYY.MM.DD"
    url: http://localhost:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
  
  - name: MySQL
    type: mysql
    url: localhost:3306
    database: grafana
    user: grafana
    password: password

  - name: MSSQL
    type: mssql
    url: localhost:1433
    database: grafana
    user: grafana
    password: "Password!"

  - name: Postgres
    type: postgres
    url: localhost:5432
    database: grafana
    user: grafana
    password: password
    jsonData:
      sslmode: "disable"

  - name: Cloudwatch
    type: cloudwatch
    editable: true
    jsonData:
      authType: credentials
      defaultRegion: eu-west-2

