  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./docker/blocks/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"

  loki-data:
    build: docker/blocks/loki/data
    command: node /home/node/data.js http://loki:3100
    depends_on:
      - loki
    # when loki starts, there might be some time while it is not
    # accepting requests, so we allow data.js to restart on failure.
    restart: "on-failure"