[run]
init_cmds = [
  ["make", "gen-go"],
  ["GO_BUILD_DEV=1", "make", "build-cli"],
  ["GO_BUILD_DEV=1", "make", "build-server"],
  ["./bin/grafana-server", "-packaging=dev", "cfg:app_mode=development"]
]
watch_all = true
follow_symlinks = true
watch_dirs = [
  "$WORKDIR/pkg",
  "$WORKDIR/public/views",
  "$WORKDIR/conf",
]
watch_exts = [".go", ".ini", ".toml", ".template.html"]
ignore_files = ["wire_gen.go"]
build_delay = 1500
cmds = [
  ["make", "gen-go"],
  ["GO_BUILD_DEV=1", "make", "build-server"],
  ["./bin/grafana-server", "-packaging=dev", "cfg:app_mode=development"]
]
