enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  '@storybook/addon-docs@6.5.16':
    peerDependencies:
      '@babel/core': ^7.0.0
      '@storybook/manager-webpack5': 6.5.16
      'webpack': 5.74.0
  '@storybook/addon-essentials@6.5.16':
    peerDependencies:
      '@storybook/components': 6.5.16
      '@storybook/core-events': 6.5.16
      '@storybook/manager-webpack5': 6.5.16
      '@storybook/theming': 6.5.16
  '@storybook/core-server@6.5.16':
    peerDependencies:
      '@babel/core': ^7.0.0
  '@storybook/core@6.5.16':
    peerDependencies:
      '@babel/core': ^7.0.0
      '@storybook/manager-webpack5': 6.5.16
  '@storybook/csf-tools@6.5.16':
    peerDependencies:
      '@babel/core': ^7.0.0
  '@storybook/mdx2-csf@0.0.3':
    dependencies:
      '@babel/types': ^7.14.8
  '@storybook/react@6.5.16':
    peerDependencies:
      '@storybook/manager-webpack5': 6.5.16
  doctrine@3.0.0:
    dependencies:
      assert: 2.0.0
  rc-time-picker@3.7.3:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1
  rc-trigger@2.6.5:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1
  react-compat-css-styled@1.0.8:
    dependencies:
      react-simple-compat: 1.2.2
  react-icons@2.2.7:
    peerDependencies:
      prop-types: '*'
  react-resizable@3.0.4:
    peerDependencies:
      react-dom: 17.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://mskelton.dev/yarn-outdated/v2'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
# Uncomment the following lines if you want to use Verdaccio local npm registry. Read more at packages/README.md
# npmScopes:
#   grafana:
#     npmRegistryServer: http://localhost:4873

# unsafeHttpWhitelist:
#   - 'localhost'
