enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "@grafana/slate-react@0.22.10-grafana":
    peerDependencies:
      slate-react: ">=0.22.0"
  "@mdx-js/loader@1.6.22":
    peerDependencies:
      react: 17.0.1
  "@storybook/addon-docs@6.4.15":
    peerDependencies:
      "@storybook/manager-webpack5": 6.4.15
  "@storybook/addon-essentials@6.4.15":
    peerDependencies:
      "@storybook/components": 6.4.15
      "@storybook/core-events": 6.4.15
      "@storybook/manager-webpack5": 6.4.15
      "@storybook/theming": 6.4.15
  "@storybook/core-server@6.4.15":
    peerDependencies:
      "@babel/core": ^7.0.0
  "@storybook/core@6.4.15":
    peerDependencies:
      "@babel/core": ^7.0.0
      "@storybook/manager-webpack5": 6.4.15
  "@storybook/csf-tools@6.4.15":
    peerDependencies:
      "@babel/core": ^7.0.0
  "@storybook/react@6.4.15":
    peerDependencies:
      "@storybook/manager-webpack5": 6.4.15
  doctrine@3.0.0:
    dependencies:
      assert: 2.0.0
  moveable@0.28.0:
    dependencies:
      "@daybrush/utils": 1.6.0
      framework-utils: ^1.1.0
  rc-time-picker@3.7.3:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1
  rc-trigger@2.6.5:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1
  react-compat-css-styled@1.0.8:
    dependencies:
      react-simple-compat: 1.2.1
  react-compat-moveable@0.16.0:
    dependencies:
      "@egjs/agent": ^2.2.1
      "@egjs/children-differ": ^1.0.1
      "@scena/matrix": 1.1.1
      css-to-mat: ^1.0.3
      gesto: ^1.7.0
      overlap-area: ^1.0.0
      react-simple-compat: 1.2.1
    peerDependencies:
      framework-utils: ^1.1.0
  react-docgen-typescript-loader@3.7.2:
    peerDependencies:
      webpack: 4.41.5
  react-icons@2.2.7:
    peerDependencies:
      prop-types: "*"
  react-resizable@3.0.4:
    peerDependencies:
      react-dom: 17.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
