# You need to run 'sysctl -w vm.max_map_count=262144' on the host machine

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0
    command: elasticsearch -E "discovery.type=single-node"
    ports:
      - "12200:9200"
      - "12300:9300"

  fake-elastic7-data:
    image: grafana/fake-data-gen
    network_mode: bridge
    environment:
      FD_DATASOURCE: elasticsearch7
      FD_PORT: 12200

  filebeat7:
    image: docker.elastic.co/beats/filebeat-oss:7.0.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./docker/blocks/elastic7/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log:ro
      - ../data/log:/var/log/grafana:ro
