  openldap:
    container_name: ldap
    build: docker/blocks/auth/openldap
    environment:
      SLAPD_PASSWORD: grafana
      SLAPD_DOMAIN: grafana.org
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "389:389"


