  openldap:
    container_name: ldap
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: grafana
      LDAP_DOMAIN: grafana.org
      LDAP_ADMIN_PASSWORD: grafana
      LDAP_SEED_INTERNAL_LDIF_PATH: /tmp/smt/
    ports:
      - 389:389
      - 636:636
    restart: unless-stopped
    volumes:
      - ./docker/blocks/auth/openldap/prepopulate/:/tmp/smt/
