  # Generate traffic by hitting http://localhost:8081
  frontend-example:
    image: ghcr.io/openzipkin/brave-example
    entrypoint: start-frontend
    ports:
      - 8081:8081
    depends_on:
      backend-example:
        condition: service_healthy
      zipkin:
        condition: service_started
  # Serves the /api endpoint the frontend uses
  backend-example:
    image: ghcr.io/openzipkin/brave-example
    entrypoint: start-backend
    depends_on:
      zipkin:
        condition: service_started
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
