name: Enterprise PR check
on:
  pull_request:
    branches:
      - main
      - 'v[0-9]+.[0-9]+.x'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Repository Dispatch
        uses: ./actions/repository-dispatch
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          repository: grafana/grafana-enterprise
          event_type: oss-pull-request
          client_payload:
            '{"source_branch": "${{ github.head_ref }}", "target_branch": "${{ github.base_ref }}", "pr_number": "${{ github.event.number }}"}'
